repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=2000']
  - repo: local
    hooks:
      - id: npm-format
        name: npm format
        entry: npm run format
        language: system
        pass_filenames: false
      - id: npm-lint
        name: npm lint
        entry: npm run lint
        language: system
        pass_filenames: false
